export const PLACES = [
  {
    id: '0',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    type: 'Entire Apartment',
    title: 'Modern Apartment in Times Square',
    description: 'Experience the heart of New York City from this stunning modern apartment located just steps away from Times Square. Features floor-to-ceiling windows with breathtaking city views, a fully equipped kitchen with stainless steel appliances, and contemporary furnishings throughout. Perfect for exploring Broadway shows, world-class dining, and iconic NYC attractions. Building amenities include 24/7 concierge service and fitness center.',
    bed: 2,
    bedroom: 1,
    oldPrice: 280,
    newPrice: 245,
    totalPrice: 1715,
    coordinate: {
      latitude: 40.7589,
      longitude: -73.9851,
    },
  },
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    type: 'Private Villa',
    title: 'Luxury Villa with Ocean View - Santorini',
    description: 'Wake up to stunning Aegean Sea views from this exclusive villa perched on the cliffs of Oia, Santorini. This traditional Cycladic-style home features a private infinity pool, spacious terraces perfect for watching the famous Santorini sunset, and elegant interiors with local artwork. The villa includes a gourmet kitchen, marble bathrooms, and premium amenities. Just minutes from charming local tavernas and boutique shops.',
    bed: 4,
    bedroom: 3,
    oldPrice: 450,
    newPrice: 380,
    totalPrice: 2660,
    coordinate: {
      latitude: 36.4618,
      longitude: 25.3753,
    },
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    type: 'Cozy Cabin',
    title: 'Mountain Retreat in Swiss Alps',
    description: 'Escape to this charming wooden chalet nestled in the beautiful Swiss Alps near Zermatt. Perfect for both summer hiking and winter skiing adventures. The cabin features a cozy fireplace, fully equipped kitchen, and panoramic mountain views from every window. Enjoy the peaceful surroundings, fresh mountain air, and easy access to hiking trails and ski slopes. Traditional Swiss architecture meets modern comfort.',
    bed: 3,
    bedroom: 2,
    oldPrice: 195,
    newPrice: 165,
    totalPrice: 1155,
    coordinate: {
      latitude: 46.0207,
      longitude: 7.7491,
    },
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    type: 'Beach House',
    title: 'Tropical Paradise in Maldives',
    description: 'Discover ultimate luxury at this overwater bungalow in the pristine waters of the Maldives. This exclusive retreat offers direct access to crystal-clear lagoons, world-class snorkeling and diving right from your doorstep. Features include a glass floor panel for underwater viewing, private deck with sun loungers, outdoor shower, and premium amenities. Perfect for romantic getaways and unforgettable sunsets over the Indian Ocean.',
    bed: 2,
    bedroom: 1,
    oldPrice: 650,
    newPrice: 575,
    totalPrice: 4025,
    coordinate: {
      latitude: 3.2028,
      longitude: 73.2207,
    },
  },
  {
    id: '4',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    type: 'Historic Townhouse',
    title: 'Victorian Townhouse in London',
    description: 'Step into history with this beautifully restored Victorian townhouse in the heart of London\'s prestigious Kensington district. Featuring original period details including ornate moldings, hardwood floors, and elegant furnishings. The house offers multiple bedrooms, a formal dining room, and a charming garden. Walking distance to Hyde Park, world-renowned museums, and excellent shopping on King\'s Road.',
    bed: 5,
    bedroom: 4,
    oldPrice: 320,
    newPrice: 285,
    totalPrice: 1995,
    coordinate: {
      latitude: 51.4994,
      longitude: -0.1746,
    },
  },
  {
    id: '5',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80',
    type: 'Modern Loft',
    title: 'Artist\'s Loft in Tokyo Shibuya',
    description: 'Experience the vibrant energy of Tokyo from this sleek modern loft in the trendy Shibuya district. This uniquely designed space features exposed brick walls, industrial lighting, and floor-to-ceiling windows overlooking the bustling city streets. Perfect location for exploring Tokyo\'s nightlife, shopping, and incredible food scene. Easy access to subway lines and major attractions including Harajuku and Shinjuku.',
    bed: 2,
    bedroom: 1,
    oldPrice: 180,
    newPrice: 155,
    totalPrice: 1085,
    coordinate: {
      latitude: 35.6598,
      longitude: 139.7006,
    },
  },
];
